### ISSUE TITLE
Linear visualization not working

### ISSUE THREAD

**Issue by G-Molano-LA** [stothard-group/cgview-js#15]
Hi! Thanks for the amazing tool.

I'm just trying to visualize a linear structure by adding the attribute `'format': 'linear'` to `settings`, but still render as circular. I would appreciate any help.

```
<!-- CG VIEWER -->
<script type="module">
    import cgview from 'https://cdn.jsdelivr.net/npm/cgview@1.6.0/+esm';

    var cgv = new CGV.Viewer('#my-viewer', {
        height: 800,
        width: 1000
    });

    json = {'cgview': {'features': [{'legend': 'Virulence',
                                        'name': 'IncX5_2, MF062700, ',
                                        'source': 'json-feature',
                                        'start': 129,
                                        'stop': 704,
                                        'type': 'CDS'}],
                          'legend': {'items': [{'decoration': 'arrow',
                                                'name': 'CDS',
                                                'swatchColor': 'rgb(111,187,111)'},
                                               {'decoration': 'arrow',
                                                'name': 'Virulence',
                                                'swatchColor': 'rgb(118,84,154)'},
                                               {'decoration': 'arrow',
                                                'name': 'BGC',
                                                'swatchColor': 'rgb(255,159,64)'},
                                               {'decoration': 'arrow',
                                                'name': 'Other',
                                                'swatchColor': 'rgb(81,160,238)'}]},
                          'sequence': {'length': 47656},
                          'settings': {'arrowHeadLength': 0.3,
                                       'backgroundColor': 'white',
                                       'format': 'linear',
                                       'showShading': 'true'},
                          'tracks': [{'dataKeys': 'json-feature',
                                      'dataMethod': 'source',
                                      'dataType': 'feature',
                                      'name': 'Features'}],
                          'version': '1.1.0'}}
    json = json.replace(/'/g, '"');

    // Load the JSON
    cgv.io.loadJSON(json);

    cgv.draw();
</script>
```

![image](https://github.com/stothard-group/cgview-js/assets/52918763/6fd688dc-7627-46b9-b6dd-eebec8037300)

Bests,

Alejandra

**Comment by sciguy** [comment]
Hi Alejandra,

Thanks for letting me know about this issue. This should be fixed in b8e2d3d. You can find the new version of CGView.js here: `docs/dist/cgview.min.js`.

Jason

**Comment by G-Molano-LA** [comment]
Hi! 
Could you maybe please provide an example to confirm that works? Mine still doesn't work with new `cgview.min.js`. Thanks a lot!

**Comment by sciguy** [comment]
Hi,

After you load your json, try calling `cgv.resize()`, this can fix issues with maps not showing up.

As for an example, I tested your json above and it worked for me. Here are the steps I followed:

1) Copy your json variable from above:
```js
// Copy the full variable from above (no need to replace single quotation marks)
json = {'cgview': {'features' ... 'version': '1.1.0'}}
```
2) Go to the cgview.js homepage: https://js.cgview.ca
3) Open the developer console in the browser and paste the json variable from step 1
4) Load the json:
```js
cgv.io.loadJSON(json);
```
5) Resize the map:
```js
cgv.resize()
```

You should see a linear map in the viewer at the bottom of the home page.

**Comment by G-Molano-LA** [comment]
Thanks a lot! With `cgv.resize()` works :)
